# Generated by Django 5.1.15 on 2026-03-20 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color for diagrams', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(max_length=200)),
                ('respondent_role', models.CharField(blank=True, max_length=200)),
                ('data', models.JSONField(default=dict, help_text='All answers keyed by question key')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='vsm.category')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. A, B, C', max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='vsm.category')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique key within the category', max_length=60)),
                ('label', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text (short)'), ('textarea', 'Textarea (long)'), ('table', 'Table (rows × columns)'), ('checklist', 'Checklist (options)')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, help_text='JSON: columns for table, items for checklist', null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='vsm.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
