# Generated by Django 5.1.15 on 2026-03-20 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('row', models.PositiveSmallIntegerField(default=0, help_text='Visual row (0=main flow, 1=secondary flow)')),
                ('work_time', models.FloatField(default=0, help_text='Process/touch time in hours')),
                ('wait_time', models.FloatField(default=0, help_text='Wait/idle time before this step in hours')),
                ('loop_factor', models.FloatField(default=0, help_text='Rework loop probability (0-1). E.g. 0.3 = 30% rework')),
                ('loop_work_extra', models.FloatField(default=0, help_text='Extra work time per loop iteration in hours')),
                ('num_people', models.PositiveSmallIntegerField(default=1)),
                ('flow_type', models.CharField(choices=[('push', 'Push'), ('pull', 'Pull')], default='push', max_length=4)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category/team responsible for this step', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vsm.category')),
                ('value_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='vsm.valuestream')),
            ],
            options={
                'ordering': ['row', 'order'],
            },
        ),
    ]
