# Generated by Django 5.1.15 on 2026-03-20 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0003_project_formresponse_project_valuestream_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('mermaid_code', models.TextField(help_text='Mermaid diagram code (graph LR, flowchart TD, etc.)')),
                ('is_default', models.BooleanField(default=False, help_text='If checked, this diagram is shown as the main diagram for the project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Leave blank for global diagrams', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='vsm.project')),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
