# Generated by Django 5.1.15 on 2026-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0004_diagram_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuestream',
            name='ai_analysis',
            field=models.TextField(blank=True, help_text='AI reasoning and analysis summary'),
        ),
        migrations.AddField(
            model_name='valuestream',
            name='generation_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI Generated')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='valuestream',
            name='source_responses',
            field=models.ManyToManyField(blank=True, help_text='FormResponses used to generate this VSM', related_name='derived_value_streams', to='vsm.formresponse'),
        ),
    ]
