# Generated by Django 5.1.15 on 2026-03-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0005_valuestream_ai_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI')], default='openai', help_text='AI provider to use for VSM generation', max_length=10)),
                ('api_key', models.CharField(help_text='API key for the selected provider', max_length=256)),
                ('endpoint', models.URLField(blank=True, default='', help_text='Custom endpoint URL. Leave blank for default OpenAI (https://api.openai.com/v1). For Azure, use: https://YOUR-RESOURCE.openai.azure.com/', max_length=300)),
                ('model_name', models.CharField(default='gpt-4o', help_text='Model / deployment name (e.g. gpt-4o, gpt-4o-mini)', max_length=100)),
                ('api_version', models.CharField(blank=True, default='2024-06-01', help_text='API version (Azure OpenAI only)', max_length=20)),
                ('temperature', models.FloatField(default=0.3, help_text='LLM temperature (0.0 = deterministic, 1.0 = creative)')),
                ('max_tokens', models.PositiveIntegerField(default=4000, help_text='Maximum tokens in LLM response')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable AI generation')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configuration',
            },
        ),
    ]
