# Generated by Django 5.1.15 on 2026-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0006_aiconfiguration_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
