# Generated by Django 5.1.15 on 2026-04-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0008_projectmembership_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuestream',
            name='ai_suggestions',
            field=models.TextField(blank=True, help_text='AI-generated improvement suggestions based on VSM results'),
        ),
    ]
