from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.models import User
from django import forms
from .models import (
    AIConfiguration, Category, Section, Question, FormResponse,
    ValueStream, ProcessStep, Project, Diagram, ProjectMembership,
)


# ── AI Configuration (singleton) ────────────────────────────────


class AIConfigurationForm(forms.ModelForm):
    """Custom form that masks the API key on display."""

    class Meta:
        model = AIConfiguration
        fields = "__all__"
        widgets = {
            "api_key": forms.PasswordInput(render_value=True),
        }


@admin.register(AIConfiguration)
class AIConfigurationAdmin(admin.ModelAdmin):
    form = AIConfigurationForm
    list_display = ("provider", "model_name", "endpoint_display", "is_active", "updated_at")
    fieldsets = (
        ("Provider", {
            "fields": ("provider", "is_active"),
        }),
        ("Credentials", {
            "fields": ("api_key", "endpoint"),
            "description": (
                "Para <b>OpenAI</b>: introduce tu API key. El endpoint es opcional "
                "(deja vacío para usar el predeterminado).<br>"
                "Para <b>Azure OpenAI</b>: introduce tu API key y el endpoint "
                "(https://YOUR-RESOURCE.openai.azure.com/)."
            ),
        }),
        ("Model", {
            "fields": ("model_name", "api_version", "temperature", "max_tokens"),
        }),
    )

    def endpoint_display(self, obj):
        return obj.endpoint or "(default)"
    endpoint_display.short_description = "Endpoint"

    def has_add_permission(self, request):
        # Only allow one instance
        return not AIConfiguration.objects.exists()

    def has_delete_permission(self, request, obj=None):
        return False


class SectionInline(admin.TabularInline):
    model = Section
    extra = 0


class QuestionInline(admin.TabularInline):
    model = Question
    extra = 0


class ProcessStepInline(admin.TabularInline):
    model = ProcessStep
    extra = 0
    fields = (
        "order", "row", "name", "category", "work_time", "wait_time",
        "loop_factor", "loop_work_extra", "num_people", "flow_type",
    )


@admin.register(Category)
class CategoryAdmin(admin.ModelAdmin):
    list_display = ("name", "slug", "color", "order")
    prepopulated_fields = {"slug": ("name",)}
    inlines = [SectionInline]


@admin.register(Section)
class SectionAdmin(admin.ModelAdmin):
    list_display = ("category", "code", "title", "order")
    list_filter = ("category",)
    inlines = [QuestionInline]


@admin.register(Question)
class QuestionAdmin(admin.ModelAdmin):
    list_display = ("key", "section", "question_type", "order")
    list_filter = ("section__category", "question_type")
    search_fields = ("key", "label")


class ProjectMembershipInline(admin.TabularInline):
    model = ProjectMembership
    extra = 1
    autocomplete_fields = ["user"]


@admin.register(Project)
class ProjectAdmin(admin.ModelAdmin):
    list_display = ("name", "slug", "color", "created_at")
    prepopulated_fields = {"slug": ("name",)}
    inlines = [ProjectMembershipInline]


# ── User Admin with project memberships ─────────────────────────

class UserProjectMembershipInline(admin.TabularInline):
    model = ProjectMembership
    extra = 1
    verbose_name = "Project Assignment"
    verbose_name_plural = "Project Assignments"


admin.site.unregister(User)


@admin.register(User)
class CustomUserAdmin(BaseUserAdmin):
    inlines = list(BaseUserAdmin.inlines or []) + [UserProjectMembershipInline]


@admin.register(FormResponse)
class FormResponseAdmin(admin.ModelAdmin):
    list_display = ("category", "project", "respondent_name", "respondent_role", "submitted_at", "updated_at")
    list_filter = ("category", "project", "submitted_at")
    readonly_fields = ("data",)


@admin.register(ValueStream)
class ValueStreamAdmin(admin.ModelAdmin):
    list_display = ("name", "slug", "project", "generation_method", "updated_at")
    list_filter = ("project", "generation_method")
    prepopulated_fields = {"slug": ("name",)}
    readonly_fields = ("ai_analysis", "ai_suggestions")
    inlines = [ProcessStepInline]
    fieldsets = (
        (None, {
            "fields": ("name", "slug", "project", "description"),
        }),
        ("AI Generation", {
            "fields": ("generation_method", "ai_analysis", "ai_suggestions", "source_responses"),
            "classes": ("collapse",),
            "description": "Fields populated automatically when VSM is generated by AI.",
        }),
    )


@admin.register(ProcessStep)
class ProcessStepAdmin(admin.ModelAdmin):
    list_display = ("name", "value_stream", "category", "order", "row", "work_time", "wait_time", "loop_factor")
    list_filter = ("value_stream", "category", "row")
    list_editable = ("order", "row", "work_time", "wait_time", "loop_factor")


@admin.register(Diagram)
class DiagramAdmin(admin.ModelAdmin):
    list_display = ("name", "project", "is_default", "updated_at")
    list_filter = ("project", "is_default")
    prepopulated_fields = {"slug": ("name",)}
    fieldsets = (
        (None, {
            "fields": ("name", "slug", "project", "description", "is_default"),
        }),
        ("Mermaid Code", {
            "fields": ("mermaid_code",),
            "description": "Paste your Mermaid diagram code here (e.g. graph LR, flowchart TD, sequenceDiagram, etc.)",
        }),
    )
